<?php include(PROJECT_DIR . '/application/controller/common/header/user.php') ?>
<div class="container">
  <div class="left">
    <?php include(PROJECT_DIR . '/application/controller/common/module/menu.php') ?>
    <?php include(PROJECT_DIR . '/application/controller/common/module/following.php') ?>
  </div>
  <div class="right">
    <?php include(PROJECT_DIR . '/application/controller/common/module/feed.php') ?>
  </div>
</div>