<?php include(PROJECT_DIR . '/application/controller/common/header/user.php') ?>
<div class="container">
  <div class="main">
    <div class="menu">
      <a class="item" href="<?php echo PROJECT_HOST ?>" title="<?php echo _('Home') ?>">
        <i class="bi bi-house"></i>
      </a><a class="item active" href="following" title="<?php echo _('Following') ?>">
        <i class="bi bi-person"></i>
        <?php if ($followingUsersTotal) { ?>
          <span><?php echo $followingUsersTotal ?></span>
        <?php } ?>
      </a><a class="item" href="bookmarks" title="<?php echo _('Bookmarks') ?>">
        <i class="bi bi-bookmarks"></i>
      </a><a class="item" href="mentions" title="<?php echo _('Mentions') ?>">
        <i class="bi bi-at"></i>
      </a><a class="item" href="messages" title="<?php echo _('Messages') ?>">
        <i class="bi bi-envelope"></i>
      </a><a class="item" href="settings" title="<?php echo _('Messages') ?>">
        <i class="bi bi-gear"></i>
      </a>
    </div>
    <div class="content">
      <?php foreach ($followingUsers as $followingUser) { ?>
        <div class="item">
          @<?php echo $followingUser['name'] ?>
        </div>
      <?php } ?>
    </div>
  </div>
  <div class="side"></div>
</div>
<div class="footer">
  <?php include(PROJECT_DIR . '/application/controller/common/footer/user.php') ?>
</div>