<?php include(PROJECT_DIR . '/application/controller/common/header/user.php') ?>
<div class="container">
  <div class="main">
    <div class="menu">
      <a class="item active" href="<?php echo PROJECT_HOST ?>" title="<?php echo _('Home') ?>">
        <i class="bi bi-house"></i>
      </a>
      <a class="item" href="following" title="<?php echo _('Following') ?>">
        <i class="bi bi-person"></i>
        <span>12</span>
      </a>
      <a class="item" href="bookmarks" title="<?php echo _('Bookmarks') ?>">
        <i class="bi bi-bookmarks"></i>
        <span>4</span>
      </a>
      <a class="item" href="mentions" title="<?php echo _('Mentions') ?>">
        <i class="bi bi-at"></i>
      </a>
      <a class="item" href="messages" title="<?php echo _('Messages') ?>">
        <i class="bi bi-envelope"></i>
      </a>
      <a class="item" href="settings" title="<?php echo _('Messages') ?>">
        <i class="bi bi-gear"></i>
      </a>
    </div>
    <form action="<?php echo PROJECT_HOST ?>" method="POST" name="post" class="post">
      <div>
        <textarea name="post" placeholder="<?php echo _('Enter your post...') ?>"></textarea>
      </div>
      <!--<span>220</span>-->
      <button><?php echo _('Send') ?></button>
    </form>
    <div class="content">
      <div class="item">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
      </div>
      <div class="item">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
      </div>
    </div>
    <div class="footer">
      <?php include(PROJECT_DIR . '/application/controller/common/footer/user.php') ?>
    </div>
  </div>
  <div class="side">

    <!-- todo
      <form action="<?php echo PROJECT_HOST ?>" method="POST" name="search" class="search">
        <input type="text" value="" placeholder="Search...">
      </form>
    -->

    <div class="suggestions">
      <h4><?php echo _('Who to follow') ?></h4>
      <h4><?php echo _('New users') ?></h4>
      <h4><?php echo _('Last activity') ?></h4>
      <h4><?php echo _('Related posts') ?></h4>
    </div>

    </div>
</div>
