<?php include(PROJECT_DIR . '/application/controller/common/header/guest.php') ?>
<div class="container">
  <div class="login">
    <h1><?php echo _('Login') ?></h1>
    <form action="login" name="login" method="POST">
      <input type="text" name="userName" value="<?php echo $userName ?>" placeholder="<?php echo _('Username') ?>" />
      <?php if ($errorUserName) { ?>
      <div class="error"><?php echo $errorUserName ?></div>
      <?php } ?>
      <input type="password" name="userPrivateKey" value="<?php echo $userPrivateKey ?>" placeholder="<?php echo _('Key') ?>" />
      <?php if ($errorUserPrivateKey) { ?>
      <div class="error"><?php echo $errorUserPrivateKey ?></div>
      <?php } ?>
      <div class="actions">
        <button class="button" type="submit"><?php echo _('Enter') ?></button>
        <a href="register"><?php echo _('Register') ?></a>
      </div>
    </form>
  </div>
</div>
<?php include(PROJECT_DIR . '/application/controller/common/footer/guest.php') ?>