<?php include(PROJECT_DIR . '/application/controller/common/header/guest.php') ?>
<div class="container">
  <div class="register">
    <h1><?php echo _('Register') ?></h1>
    <p><?php echo sprintf(_('New user can be registered %s.'), $nextUserRegistrationTime) ?></p>
    <div class="actions">
      <a class="button" href="login"><?php echo _('Login') ?></a>
    </div>
  </div>
</div>
<?php include(PROJECT_DIR . '/application/controller/common/footer/guest.php') ?>