<?php include(PROJECT_DIR . '/application/controller/common/header/guest.php') ?>
<div class="container">
  <div class="register">
    <h1><?php echo _('Register') ?></h1>
    <form action="register" name="register" method="POST">
      <input type="text" name="userName" value="<?php echo $userName ?>" placeholder="<?php echo _('Username') ?>" />
      <?php if ($errorUserName) { ?>
      <div class="error"><?php echo $errorUserName ?></div>
      <?php } ?>
      <div class="actions">
        <button class="button" type="submit"><?php echo sprintf(_('~ %s'), $blockEstimated) ?></button>
        <a href="login"><?php echo _('Login') ?></a>
      </div>
    </form>
  </div>
</div>
<?php include(PROJECT_DIR . '/application/controller/common/footer/guest.php') ?>