<?php include(PROJECT_DIR . '/application/controller/common/header/guest.php') ?>
<div class="container">
  <div class="register">
    <h1><?php echo _('Welcome') ?></h1>
    <p><?php echo sprintf(_('Account <strong class="username">@%s</strong> in registration!'), $userName); ?></p>
    <p><?php echo sprintf(_('Please, wait for block %s to enter the twister and keep the secret key in safety place:'), $blockEstimated); ?></p>
    <pre class="key"><?php echo $userPrivateKey; ?></pre>
    <div class="actions">
      <a class="button" href="login"><?php echo _('Login') ?></a>
    </div>
  </div>
</div>
<?php include(PROJECT_DIR . '/application/controller/common/footer/guest.php') ?>