<?php include(PROJECT_DIR . '/application/controller/common/header.php') ?>
<div class="mw-1024 mx-auto of-hidden">
  <div class="mw-360 mx-auto my-100 bg-c-4 b-r-3 py-28 px-24">
    <h1 class="f-size-65 f-normal mb-20 t-center"><?php echo _('404') ?></h1>
    <p class="t-center"><?php echo _('Page not Found') ?></p>
  </div>
</div>
<?php include(PROJECT_DIR . '/application/controller/common/footer.php') ?>