<div class="moduleMenu" id="moduleMenu">
  <a class="item" href="/" title="<?php echo _('Home') ?>">
    <i class="bi bi-house"></i>
  </a><a class="item" href="people" title="<?php echo _('People') ?>">
    <i class="bi bi-person"></i>
    <span></span>
  </a><a class="item" href="#todo" title="<?php echo _('Bookmarks') ?>">
    <i class="bi bi-bookmarks"></i>
    <span></span>
  </a><a class="item" href="#todo" title="<?php echo _('Mentions') ?>">
    <i class="bi bi-at"></i>
    <span></span>
  </a><a class="item" href="#todo" title="<?php echo _('Messages') ?>">
    <i class="bi bi-envelope"></i>
    <span></span>
  </a><a class="item" href="settings" title="<?php echo _('Settings') ?>">
    <i class="bi bi-gear"></i>
  </a>
</div>