<div class="modulePost" id="modulePost">
  <form action="/" method="POST" name="post">
    <div class="avatar">
      <img src="" alt="" />
    </div>
    <div class="message">
      <textarea name="post" placeholder="<?php echo _('Enter your post...') ?>"></textarea>
    </div>
    <div class="action">
      <div class="button" onclick="ModulePost.add()"><?php echo _('Send') ?></div>
    </div>
  </form>
</div>