<div class="modulePost" id="modulePost">
  <form action="/" method="POST" name="post">
    <div class="avatar">
      <img src="" alt="" id="modulePostAvatar" />
    </div>
    <div class="message">
      <textarea name="post" placeholder="<?php echo _('Enter your post...') ?>" id="modulePostMessage"></textarea>
    </div>
    <div class="preview" id="modulePostPreview">
    <div class="title">
      <i class="bi bi-chat-right-dots" title="<?php echo _('Preview') ?>"></i>
    </div>
    <div class="text"></div>
    </div>
    <div class="action">
      <div class="button" id="modulePostSend"><?php echo _('Send') ?></div>
    </div>
</div>