  <div class="t-center c-2">
    <p><small><?php echo sprintf(_('<a class="c-2" href="%s">TA</a> Cloud is the open source web interface to interact <a class="c-2" href="%s">twister network</a> without node installation.'), 'https://twisterarmy.github.io', 'http://twister.net.co') ?></small></p>
    <p><small><?php echo _('* software in the development. Import existing wallets on your own risk.') ?></small></p>
    <p><small><?php echo sprintf(_('version: %s'), SERVER_VERSION) ?></small></p>
  </div>
</body>