  <div class="t-center c-2">
    <p><small><?php echo sprintf(_('<a class="c-2" href="%s">TA</a> Cloud is the <a class="c-2" href="%s">open source</a> web interface to interact <a class="c-2" href="%s">twister network</a> without node installation.'), 'https://twisterarmy.github.io', 'https://github.com/twisterarmy/cloud-server', 'http://twister.net.co') ?></small></p>
    <p><small><?php echo _('* software under development. Import existing wallets on your own risk.') ?></small></p>
    <p class="mt-20"><small><?php echo sprintf(_('version %s'), SERVER_VERSION) ?> <i class="bi bi-suit-heart"></i></small></p>
    <p class="mt-10 f-size-16"></p>
  </div>
</body>