<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title><?php echo _('Login twister | Twisterarmy Cloud') ?></title>
  <meta name="description" content="Twisterarmy Cloud is the open source web interface to interact twister network without node installation." />
  <link rel="stylesheet" type="text/css" href="css/font.css" />
  <link rel="stylesheet" type="text/css" href="css/bi.css" />
  <link rel="stylesheet" type="text/css" href="css/common.css" />
  <link rel="stylesheet" type="text/css" href="css/mobile.css" />
  <script src="js/jquery.js"></script>
</head>
<body class="bg-c-1 bg-img-1 c-0">