  <div class="footer">
    <p><small><?php echo sprintf(_('Twisterarmy Cloud is the <a href="%s">Open Source</a> web interface to interact <a href="%s">Twister Network</a> remotely.'), 'https://github.com/twisterarmy/cloud-server', 'http://twister.net.co') ?></small></p>
    <p><small><?php echo _('* software under development. Import existing wallets on your own risk.') ?></small></p>
    <p><small><?php echo sprintf(_('version %s'), SERVER_VERSION) ?> <i class="bi bi-suit-heart"></i></small></p>
  </div>
</body>