<?php include(PROJECT_DIR . '/application/controller/common/header/user.php') ?>
<div class="container">
  <div class="right">
    <?php include(PROJECT_DIR . '/application/controller/common/module/menu.php') ?>
    <?php include(PROJECT_DIR . '/application/controller/common/module/settings.php') ?>
  </div>
  <div class="left">
    <div class="settingsProfile">
      <h1><?php echo $pageTitle ?></h1>
      <form action="settings" name="profile" enctype="multipart/form-data" method="POST">
        <div class="avatar">
          <img src="" alt="" id="settingsProfileAvatarImage" />
          <input name="avatar" id="settingsProfileAvatar" type="file" value="" />
        </div>
        <label for="settingsProfileFullName"><?php echo _('Full name') ?></label>
        <input type="text" name="fullName" id="settingsProfileFullName" value="" placeholder="<?php echo _('Not provided') ?>" />
        <label for="settingsProfileLocation"><?php echo _('Location') ?></label>
        <input type="text" name="location" id="settingsProfileLocation" value="" placeholder="<?php echo _('Not provided') ?>" />
        <label for="settingsProfileURL"><?php echo _('Website') ?></label>
        <input type="text" name="url" id="settingsProfileURL" value="" placeholder="<?php echo _('Not provided') ?>" />
        <label for="settingsProfileBitMessage"><?php echo _('BitMessage') ?></label>
        <input type="text" name="bitMessage" id="settingsProfileBitMessage" value="" placeholder="<?php echo _('Not provided') ?>" />
        <label for="settingsProfileTOX"><?php echo _('TOX') ?></label>
        <input type="text" name="tox" id="settingsProfileTOX" value="" placeholder="<?php echo _('Not provided') ?>" />
        <label for="settingsProfileBio"><?php echo _('Bio') ?></label>
        <textarea name="bio" id="settingsProfileBio" placeholder="<?php echo _('Not provided') ?>"></textarea>
        <div class="actions">
          <span class="success" id="settingsProfileActionsSuccess"><?php echo $successMessage ?></span>
          <button type="submit"><?php echo _('Save') ?></button>
        </div>
      </form>
    </div>
  </div>
</div>