<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title><?php echo $metaTitle ?></title>
  <base href="<?php echo PROJECT_HOST ?>" />
  <meta name="description" content="Twisterarmy Cloud is the open source web interface to interact twister network without node installation." />
  <link rel="shortcut icon" href="/image/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/image/favicon.ico" type="image/x-icon">
  <link rel="stylesheet" type="text/css" href="css/template/default/font.css" />
  <link rel="stylesheet" type="text/css" href="css/template/default/bi.css" />
  <link rel="stylesheet" type="text/css" href="css/template/default/app.css" />
  <link rel="stylesheet" type="text/css" href="css/template/default/mobile.css?v=3" />
  <?php foreach ($metaStyles as $metaStyle) { ?>
  <link rel="stylesheet" type="text/css" href="<?php echo $metaStyle ?>" />
  <?php } ?>
  <script src="js/jquery.js"></script>
  <?php foreach ($metaScripts as $metaScript) { ?>
  <script src="<?php echo $metaScript ?>"></script>
  <?php } ?>
</head>
<body>
  <div class="header">
    <div class="container">
      <div class="left">
        <a class="logo" href="/">Twisterarmy <i><?php echo _('Cloud') ?></i></a>
      </div>
      <div class="right">
        <small><?php echo sprintf(_('Network status: %s users in %s blocks'), $usersTotal, $blocksTotal) ?></small>
        <a class="menu" href="https://github.com/twisterarmy/cloud-server" target="_blank"><i class="bi bi-github"></i></a>
        <a class="menu" href="https://github.com/twisterarmy/cloud-server/issues" target="_blank"><i class="bi bi-question-circle"></i></a>
      </div>
    </div>
  </div>